# Generated by Django 5.1.1 on 2024-09-20 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0007_course_course_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("generated_content", models.TextField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_contents",
                        to="mysite.lecture",
                    ),
                ),
            ],
        ),
    ]
