# Generated by Django 5.1.1 on 2024-09-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0008_aicontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_slug",
            field=models.SlugField(default="-"),
        ),
    ]
