# Generated by Django 5.1.1 on 2024-09-20 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0009_section_section_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="section_slug",
        ),
    ]
