# Generated by Django 5.1.1 on 2024-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0011_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="thumbnail_url",
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
