# Generated by Django 5.1.1 on 2024-09-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0012_remove_course_thumbnail_url_course_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="video_url",
            field=models.CharField(max_length=255),
        ),
    ]
